### ISSUE TITLE
some functions

### ISSUE THREAD

**Issue by MineSunshineone** [kugge/Kaiiju#38]
### Is your feature request related to a problem?

Because designed for vanilla/anarchy servers, I think some features of Purpur are very useful

### Describe the solution you'd like.

such as:
end_portal:
         safe-teleporting: false
sand:
         fix-duping: false
tps-catchup: true
server-mod-name
tpsbar
If possible, I think it would also be nice to add some optimization patches, e.g.
Pufferfish Patch: https://github.com/pufferfish-gg/Pufferfish/tree/ver/1.19/patches

C2ME
VMP
SMOOTH BOOST
Lithium

### Describe alternatives you've considered.

Of course it is also possible to create Folia-Purpur and add some mod optimization algorithms

**Comment by sofianedjerbi** [comment]
Implementing all Purpur features into Folia isn't that relevant that it was before, most of them should be implemented with plugins (riding entities..)

But those seem essential:
- safe-teleporting/fix-duping
- server-mod-name
- tpsbar/msptbar (AS A PLUGIN)
- disable mojang profiler

Some pufferfish patches could be implemented too.
Thanks for the suggestion

**Comment by MineSunshineone** [comment]
Purpur is too bloated, so it's just an alternative :), it would be better if the above solution can be implemented

**Comment by xymb-endcrystalme** [comment]
> disable mojang profiler

Isn't that already provided by Paper?

I'm *against* adding random optimizations. Every change is an additional pain. Thus, every optimization needs to bring a significant improvement, not a random "1% here".

As for Pufferfish, the only optimization I see there is https://github.com/pufferfish-gg/Pufferfish/blob/ver/1.19/patches/api/0005-Optimize-map-rendering.patch ?

Is map rendering a problem?

> C2ME
> VMP
> SMOOTH BOOST
> Lithium

IMO each and **every** one of the patches needs to be proposed and evaluated one by one.

For example IMO that Lithium optimization where they precalculate sine tables is just silly.

I'd love to see some benchmarks before someone accepts that patch.

We don't have spare programming power to debug and maintain random patches. So let's focus on most important stuff.

**Comment by MineSunshineone** [comment]
> > 禁用 Mojang 探查器
> 
> 这不是纸业已经提供了吗？
> 
> 我_反对_添加随机优化。每一次改变都是额外的痛苦。因此，每次优化都需要带来显着的改进，而不是随机的“此处 1%”。
> 
> 至于河豚，我看到的唯一优化是 https://github.com/pufferfish-gg/Pufferfish/blob/ver/1.19/patches/api/0005-Optimize-map-rendering.patch？
> 
> 地图渲染有问题吗？
> 
> > C2ME VMP 平滑升压锂
> 
> IMO需要逐一提出和评估每个补丁。
> 
> 例如，IMO 认为他们预先计算正弦表的锂优化只是愚蠢的。
> 
> 我很想在有人接受该补丁之前看到一些基准测试。
> 
> 我们没有多余的编程能力来调试和维护随机补丁。因此，让我们专注于最重要的事情。

maybe DAB and Partial Asynchronous Processing

**Comment by sofianedjerbi** [comment]
Sand duping is added back with [FoliaFlow](https://github.com/Hynse/FoliaFlow/tree/master), which i contributed massively  
Void trading is added back with a patch and with [Kaiivoid](https://github.com/KaiijuMC/Kaiivoid)
TPS catchup don't make sense since we don't know what we should catch
server-mod-name is implemented
tps-bar should be a plugin

I close this issue, feel free to suggest other patches.

**Comment by MineSunshineone** [comment]
what about this ? https://github.com/Bloom-host/Petal/tree/ver/1.19.2/patches/server

**Comment by sofianedjerbi** [comment]
This requires heavy stability tests/benchmarks, but why not. They need to be rewritten though
