### ISSUE TITLE
Cannot add effects to entities asynchronously crash

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [kugge/Kaiiju#54]
This is last log: https://paste.ubuntu.com/p/2DpfXXq2n3/

Maybe this crash is datapacket, but I think this bug is form Folia, because I can get this crash in any Paper or it fork's, like Purpur

I think to fix this crash only can use server patch, this crash is by hard mode effect spider, I 100% can believe this crash is made by spider because if I change server's mode to normal or other difficulty mode I never get this crash, I think this crash is papermc's asyn bug, it can't use plugin to fix it, I thought

**and system didn't think this crash is a crash so system didn't create a crash-report file**

Ver: ![Screenshot_20230509-171326.png](https://user-images.githubusercontent.com/71379165/237051047-f3cb0fc3-f700-4cf6-a667-54ab261f1c9d.png)

Plugins![Screenshot_20230509-171446.png](https://user-images.githubusercontent.com/71379165/237051370-6b955326-0498-4e9a-b6c2-903eee2e3f6d.png)

Datapacket:![Screenshot_20230509-171502.png](https://user-images.githubusercontent.com/71379165/237051430-6b47457c-dcd1-45dd-a80f-1871d1108ec2.png)

**Comment by sofianedjerbi** [comment]
This bug is from folia. We can always add an hotfix since it is easy to fix..

**Comment by xiaoyueyoqwq** [comment]
> This bug is from folia. We can always add an hotfix since it is easy to fix..

oh that's great, I'm very happy to hear that :)

**Comment by sofianedjerbi** [comment]
theres 2 possible "hotfixes":
- Do not give the player that effect if he's not in the right thread
- Give him the effect 1 tick later (not vanilla behavior, is that important ? does it broke some farms ?)

**Comment by sofianedjerbi** [comment]
please try to reproduce with the latest build

**Comment by xiaoyueyoqwq** [comment]
> 

okay, I'd try it now

**Comment by xiaoyueyoqwq** [comment]
> please try to reproduce with the latest build

I get this crash in 1min ago

this is log:https://paste.ubuntu.com/p/yz75kngzVQ/

maybe I think this crash is about chunk tick, the same as my another issue?

**Comment by sofianedjerbi** [comment]
I fixed the crash that happen when raid finishes, lemme fix that one too

> > please try to reproduce with the latest build
> 
> I get this crash in 1min ago
> 
> this is log:https://paste.ubuntu.com/p/yz75kngzVQ/
> 
> maybe I think this crash is about chunk tick, the same as my another issue?

**Comment by sofianedjerbi** [comment]
Please try again with latest build

**Comment by xiaoyueyoqwq** [comment]
> Please try again with latest build 

okay, thx for your help!

**Comment by xiaoyueyoqwq** [comment]
> Please try again with latest build

I think this bug has been fix with you ;)
