### ISSUE TITLE
net.minecraft.ReportedException: Exception ticking world

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [kugge/Kaiiju#55]
Logs: https://paste.ubuntu.com/p/CcRv93rtFW/

Well, I think this crash should be a bug in Folia, and I have also encountered several crashes before this, the server will uninstall all plugins but the player will not exit the server because of this, they can even send messages, but they cannot interact with the blocks, and the server cannot save maps and player data normally, so if this crash is triggered, some of the player data of the server may be lost

Plugins and datapacks list I think you are already know ;)

ver: This server is running Kaiiju version git-Kaiiju-"57bd665" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 57bd665 on ver/1.19.4)
You are running the latest version

**Comment by sofianedjerbi** [comment]
I know this crash.. i don't know if i'm able to fix it..

**Comment by xiaoyueyoqwq** [comment]
> I know this crash.. i don't know if i'm able to fix it..

i think you need more information:
![image](https://github.com/KaiijuMC/Kaiiju/assets/71379165/019e0bdc-f080-42de-960d-82c2cde64e54)

This play use command /back when server was crash, perhaps this error is still related to teleportation, as was the previous player teleportation server block crash, like _Cannot move entity off-main_ issue

**Comment by sofianedjerbi** [comment]
I've been trying to fix this for weeks. It always happen on teleportation or on huge chunk loading. I'm going to add more debug info

**Comment by sofianedjerbi** [comment]
Can you please test this branch

https://github.com/KaiijuMC/Kaiiju/tree/dev/fixes

It kick the player instead of crashing the server
Note this might lead to unexpected behaviour, so it need tests

I'll close this issue while waiting for upstream changes

**Comment by xiaoyueyoqwq** [comment]
> Can you please test this branch
> 
> https://github.com/KaiijuMC/Kaiiju/tree/dev/fixes
> 
> It kick the player instead of crashing the server
> Note this might lead to unexpected behaviour, so it need tests
> 
> I'll close this issue while waiting for upstream changes

Okay, I try it now

**Comment by xiaoyueyoqwq** [comment]
> Can you please test this branch
> 
> https://github.com/KaiijuMC/Kaiiju/tree/dev/fixes
> 
> It kick the player instead of crashing the server Note this might lead to unexpected behaviour, so it need tests
> 
> I'll close this issue while waiting for upstream changes

Maybe you can try to add this branch to Releases now

**Comment by sofianedjerbi** [comment]
The workaround seems to work:

```diff
  [mar. 00:03:37 INFO  Server/PlayerConnection] skoaboi issued server command: /tp 0 100 0
  [mar. 00:03:37 INFO  Server] [skoaboi: Teleported skoaboi to 0.500000, 100.000000, 0.500000]
  [mar. 00:03:37 INFO  Server/PlayerConnection] skoaboi lost connection: Already sent chunk [0, -3] in world world
  [mar. 00:03:37 INFO  voicechat] Disconnecting client skoaboi
  [mar. 00:03:37 INFO  Server] skoaboi left the game
- [mar. 00:03:37 ERROR Minecraft] Already sent chunk [0, -3] in world world
```
No crash, just an error
