### ISSUE TITLE
Flame people in the server do not drop flame sticks

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [kugge/Kaiiju#58]
### Expected behavior

The Flame Man should drop the Flaming Wand after being killed by the player

### Observed/Actual behavior

The Flame Man does not drop the Flame Stick after being killed by the player

### Steps/models to reproduce

Find the Flame Man and take them out

### Plugin and Datapack List

[18:41:02 INFO]: Server Plugins (25):
[18:41:02 INFO]: Paper Plugins:
[18:41:02 INFO]:  - FoliaFlow, HuskHomes
[18:41:02 INFO]: Bukkit Plugins:
[18:41:02 INFO]:  - BlockLocker, Bolt, Chunky, CoreProtect, FancyFirework, FancyNpcs, FarmControl, FastAsyncWorldEdit, FramedImage, FreedomChat
[18:41:02 INFO]:  GreenChunk, GrimAC, GSit, InvSeePlusPlus, Kaiivoid, LaggRemover, LuckPerms, PAPIProxyBridge, Pl3xMap, PlaceholderAPI
[18:41:02 INFO]:  spark, ViaBackwards, ViaVersion

datapacket: [datapacket.zip](https://github.com/KaiijuMC/Kaiiju/files/11553560/datapacket.zip)

### Kaiiju version

[18:41:15 INFO]: Checking version, please wait...
[18:41:16 INFO]: This server is running Kaiiju version git-Kaiiju-"57d8906" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 57d8906 on ver/1.19.4)
You are running the latest version
Previous version: git-Kaiiju-"1139843" (MC: 1.19.4)

### Other

this is spark report, maybe it can help you to find question: https://spark.lucko.me/9bfSrmstU9

**Comment by sofianedjerbi** [comment]
Kaiiju will not implement Folia missing datapack functions since everything will be rewritten by Folia

**Comment by xiaoyueyoqwq** [comment]
> Kaiiju will not implement Folia missing datapack functions since everything will be rewritten by Folia

yeal, i test it in normal Kaiju Server, maybe there are any datapacket change vanilla
By the way, would Kaiju consider introducing some biooptimization mechanisms for pufferfish? I think this has a big impact on server performance

**Comment by sofianedjerbi** [comment]
> > Kaiiju will not implement Folia missing datapack functions since everything will be rewritten by Folia
> 
> yeal, i test it in normal Kaiju Server, maybe there are any datapacket change vanilla
> By the way, would Kaiju consider introducing some biooptimization mechanisms for pufferfish? I think this has a big impact on server performance

DAB?

**Comment by sofianedjerbi** [comment]
Closed (scoreboards should be fixed by folia)

**Comment by xiaoyueyoqwq** [comment]
> > > Kaiiju will not implement Folia missing datapack functions since everything will be rewritten by Folia
> > 
> > yeal, i test it in normal Kaiju Server, maybe there are any datapacket change vanilla
> > By the way, would Kaiju consider introducing some biooptimization mechanisms for pufferfish? I think this has a big impact on server performance
> 
> DAB?

yes
