### ISSUE TITLE
updata1.20.1

### ISSUE THREAD

**Issue by Lythrilla** [kugge/Kaiiju#63]
### Is your feature request related to a problem?

no

### Describe the solution you'd like.

updata1.20.1

### Describe alternatives you've considered.

a

### Other

a

**Comment by sofianedjerbi** [comment]
dev/1.20 folia / kaiiju

**Comment by xiaoyueyoqwq** [comment]
> dev/1.20 folia / kaiiju

only dev? Seems not very stable
How soon do you plan to launch the official version?

**Comment by sofianedjerbi** [comment]
> > dev/1.20 folia / kaiiju
> 
> only dev? Seems not very stable How soon do you plan to launch the official version?

When folia will fix Scheduling chunk load off-main. Did a quickfix for my own server, this is the last issue left

**Comment by xiaoyueyoqwq** [comment]
> > > dev/1.20 folia / kaiiju
> > 
> > 
> > only dev? Seems not very stable How soon do you plan to launch the official version?
> 
> When folia will fix Scheduling chunk load off-main. Did a quickfix for my own server, this is the last issue left

maybe paper was fix it, I'm not for sure
take a look pls: https://github.com/PaperMC/Folia/issues/62
