### ISSUE TITLE
Compatible with String Duplication

### ISSUE THREAD

**Issue by Lythrilla** [kugge/Kaiiju#64]
### Is your feature request related to a problem?

Compatible with String Duplication

### Describe the solution you'd like.

Compatible with String Duplication

### Describe alternatives you've considered.

no

**Comment by sofianedjerbi** [comment]
String duplication is already supported.
`fix-tripwire-state-inconsistency: false`

**Comment by Lythrilla** [comment]
thx

**Comment by sofianedjerbi** [comment]
if you have questions feel free to ask on discord
