### ISSUE TITLE
merging DirtyFolia

### ISSUE THREAD

**Issue by Lythrilla** [kugge/Kaiiju#65]
### Is your feature request related to a problem?

support more Only Bukkit-API plugins

### Describe the solution you'd like.

Can you try merging DirtyFolia

### Describe alternatives you've considered.

1

### Other

1

**Comment by xymb-endcrystalme** [comment]
What's DirtyFolia? Googling "DirtyFolia" Minecraft shows 0 results.

**Comment by Lythrilla** [comment]
https://github.com/killerprojecte/Folia

**Comment by Lythrilla** [comment]
DirtyFolia is a project to make Original Folia support more Only Bukkit-API plugins

**Comment by sofianedjerbi** [comment]
sounds like a bad idea

**Comment by sofianedjerbi** [comment]
DirtyFolia will not be merged because it contains highly unstable patches
