### ISSUE TITLE
Add some carpet features

### ISSUE THREAD

**Issue by Lythrilla** [kugge/Kaiiju#66]
### Is your feature request related to a problem?

Players need

### Describe the solution you'd like.

For example, bots

### Describe alternatives you've considered.

  1

### Other

 1

**Comment by xiaoyueyoqwq** [comment]
This is paper, not fabric
if you want to use carpet, pls go to download fabric server core

**Comment by sofianedjerbi** [comment]
Create or use a plugin if you want bots
