### ISSUE TITLE
Some issue

### ISSUE THREAD

**Issue by Koyorice** [kugge/Kaiiju#67]
Can I install this server core directly on my existing Folia?  Are world files automatically converted to the correct format?

**Comment by mani1232** [comment]
By default Kaiiju use Anvil (default minecraft world format)

**Comment by mani1232** [comment]
If you want you can convert it to linear

**Comment by Koyorice** [comment]
I just checked the docs for the conversion and I think I understand how it works, thanks for your help and replies!
