### ISSUE TITLE
java.lang.Throwable: net.minecraft.ReportedException: Feature placement

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [kugge/Kaiiju#68]
### Expected behavior

server normal running

### Observed/Actual behavior

server was crash

### Steps/models to reproduce

none

### Plugin and Datapack List

![image](https://github.com/KaiijuMC/Kaiiju/assets/71379165/f7f8067b-10d9-402b-95f9-97f6033addb9)
![image](https://github.com/KaiijuMC/Kaiiju/assets/71379165/6746fe78-37a7-425f-b63f-193cacd1070a)

### Kaiiju version

This server is running Kaiiju version git-Kaiiju-"6657b9c" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 6657b9c on ver/1.20.1)
You are running the latest version
Previous version: git-Kaiiju-"3176184" (MC: 1.20.1)

### Other

this is err logs: https://paste.ubuntu.com/p/JQDjckPHG4/

**Comment by xiaoyueyoqwq** [comment]
another crash logs: https://paste.ubuntu.com/p/dbBgQ9yXZH/

**Comment by xiaoyueyoqwq** [comment]
another logs: https://paste.ubuntu.com/p/n6NgdjWX4Q/

**Comment by sofianedjerbi** [comment]
Can you reproduce on Folia ? Seems like a datapack compatibility error

**Comment by sofianedjerbi** [comment]
Pastes are unavailable, and bug should be reported to Folia, likely an unimplemented feature for datapacks.
