### ISSUE TITLE
Folia patches

### ISSUE THREAD

**Issue by KonusIntelliJ** [kugge/Kaiiju#69]
### Is your feature request related to a problem?

Hey, why u not commit your patches in folia?
Only was 2 patches.
![image](https://github.com/KaiijuMC/Kaiiju/assets/62984001/d047e2aa-4428-4c5d-9e09-4d58cf318717)

### Describe the solution you'd like.

-

### Describe alternatives you've considered.

-

**Comment by sofianedjerbi** [comment]
Which patches do you want me to commit to Folia ?

**Comment by KonusIntelliJ** [comment]
Teleport (last patch)

**Comment by xymb-endcrystalme** [comment]
You forgot to link the actual patches.
We can't really get those patches from a screenshot..

**Comment by sofianedjerbi** [comment]
I think i'll push the vanilla teleportation patch, the teleport api fix & the spider thread crash fix

**Comment by Evolum** [comment]
Thanks, i will wait.

**Comment by KonusIntelliJ** [comment]
Thanks, I will wait.
