### ISSUE TITLE
Desync Problem

### ISSUE THREAD

**Issue by kolderz** [kugge/Kaiiju#70]
### Expected behavior

The player position should be sync correctly. 

### Observed/Actual behavior

Player got desync.

### Steps/models to reproduce

Player 1 join server and Player 2 join the server.

### Plugin and Datapack List

None

### Kaiiju version

This server is running Kaiiju version git-Kaiiju-"8c562b0" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 8c562b0 on ver/1.20.1)

### Other

Player 1 POV: 
![player1pov](https://github.com/KaiijuMC/Kaiiju/assets/10612667/198a23d1-d3fb-4f10-963f-75809035a65a)
Player 2 POV:
![player2pov](https://github.com/KaiijuMC/Kaiiju/assets/10612667/cb9b1728-ffac-4bcb-874d-8828c03ac7bb)

**Comment by kolderz** [comment]
This also happens with folia.
![image](https://github.com/KaiijuMC/Kaiiju/assets/10612667/3f100852-88fe-4507-915c-749c2c593577)
![image](https://github.com/KaiijuMC/Kaiiju/assets/10612667/52f88d7a-c434-4a32-80b6-4d54fbe91233)

**Comment by sofianedjerbi** [comment]
Caused by internet issues
