### ISSUE TITLE
FAQ WIKI about feature.

### ISSUE THREAD

**Issue by ghost** [kugge/Kaiiju#76]
### Is your feature request related to a problem?

yes, a misunderstanding of what feature impact which part of the server.

### Describe the solution you'd like.

We need an explaining about what's under the optimization section of kaiiju for those:

disable-ensure-tick-thread-checks
disable-arm-swing-event
disable-player-stats
shared-random-for-players

The goal is to understand  what option help for.

### Describe alternatives you've considered.

we just add a comment in the config file explaining how each option have an impact on performances.

**Comment by sofianedjerbi** [comment]
Done
