### ISSUE TITLE
some mod support

### ISSUE THREAD

**Issue by bluefish-08** [kugge/Kaiiju#85]
### Is your feature request related to a problem?

none

### Describe the solution you'd like.

I hope kaiiju adding pca support, as well as syncmatica, jade, appleskin, xaeromap

### Describe alternatives you've considered.

none

**Comment by sofianedjerbi** [comment]
Such features should be provided by plugins, example: [AppleSkinSpigot](https://github.com/jmattingley23/AppleSkinSpigot)

**Comment by bluefish-08** [comment]
Can you add a dummy function, like carpet, for players to hang up the phone
