### ISSUE TITLE
sand-duplication:true，Open or not dupe sand

### ISSUE THREAD

**Issue by haoge114** [kugge/Kaiiju#86]
### Expected behavior

Hello, when I used the dupe sand machine in my kaiiju182, I found the sand in the main world dupe. There is no sand in the end world. I think this is a bug, because neither false nor true can normal dupe sand.

### Observed/Actual behavior

Can't dupe sand

### Steps/models to reproduce

Arbitrary dupe sand machine

### Plugin and Datapack List

BlockLocker, floodgate, Geyser-Spigot, HynseBackup, RiceMotd,HuskHomes

### Kaiiju version

This server is running Kaiiju version git-Kaiiju-"40d5526" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 40d5526 on ver/1.20.1)

**Comment by sofianedjerbi** [comment]
Disable safe teleportation in kaiiju yml
